url: "https://www.muettergenesung-kur.de/" #
baseurl: "/"
title: ""

collections:
  stellenanzeigen:
    output: true
    permalink: /stellenanzeigen/:name/

  landingpage-einrichtung:
    output: true
    permalink: /kurklinik/:name/

  gaestebuch:
    output: false

  haeufige_fragen:
    output: false

  kommen_sie_in_unser_team:
    output: false

  # Kurtermine

  kurtermine_lossburg:
    output: true
    permalink: /kurtermine/lossburg/:name/

  kurtermine_scheidegg:
    output: true
    permalink: /kurtermine/scheidegg/:name/

  kurtermine_badwurzach:
    output: true
    permalink: /kurtermine/badwurzach/:name/

defaults:
  - scope:
      path: "_kurtermine_*"
    values:
      layout: "kurtermin_anmeldung"
      title: "Kuranmeldung"

exclude:
  - netlify/functions
