url: "https://astounding-blancmange-bbba79.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/"
title: "" # the name of your site, e.g. ACME Corp.

collections:
  stellenanzeigen:
    output: true
    permalink: /stellenanzeigen/:name/

  landingpage-einrichtung:
    output: true
    permalink: /kurklinik/:name/

  kurtermine_badwurzach: {}

  kurtermine_lossburg: {}

  kurtermine_scheidegg: {}

  gaestebuch:
    output: false

  haeufige_fragen:
    output: false

  kommen_sie_in_unser_team:
    output: false

exclude:
  - netlify/functions
